### ISSUE TITLE
not a function 

### ISSUE THREAD

**Issue by OFFchase** [Poker1st/ModMail#4]
PS C:\Users\aminy\Documents\GitHub\another> node .
Provided token: NzI4MzMyNTkxNzkwMjkzMDQ0.XwDgaw.***************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 1000
[WS => Manager] Spawning shards: 0
[WS => Shard 0] [CONNECT]
    Gateway    : wss://gateway.discord.gg/
    Version    : 6
    Encoding   : json
    Compression: none
[WS => Shard 0] Setting a HELLO timeout for 20s.
[WS => Shard 0] [CONNECTED] wss://gateway.discord.gg/?v=6&encoding=json in 363ms
[WS => Shard 0] Clearing the HELLO timeout.
[WS => Shard 0] Setting a heartbeat interval for 41250ms.
[WS => Shard 0] [IDENTIFY] Shard 0/1
[WS => Shard 0] [READY] Session ebd4868ca26df37b64bda8addadbd958.
[WS => Shard 0] [ReadyHeartbeat] Sending a heartbeat.
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
(node:3888) UnhandledPromiseRejectionWarning: TypeError: client.user.setGame is not a function
    at Client.<anonymous> (C:\Users\aminy\Documents\GitHub\another\index.js:16:17)
    at Client.emit (events.js:314:20)
    at WebSocketManager.triggerClientReady (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:314:20)
    at WebSocketShard.checkReady (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketShard.js:467:12)  
    at WebSocketShard.onPacket (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketShard.js:439:16)    
    at WebSocketShard.onMessage (C:\Users\aminy\Documents\GitHub\another\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)   
    at WebSocket.onMessage (C:\Users\aminy\Documents\GitHub\another\node_modules\ws\lib\event-target.js:125:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[WS => Shard 0] Heartbeat acknowledged, latency of 153ms.
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 154ms.
(node:3888) UnhandledPromiseRejectionWarning: TypeError: client.guilds.get is not a function
    at Client.<anonymous> (C:\Users\aminy\Documents\GitHub\another\index.js:41:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[WS => Shard 0] [HeartbeatTimer] Sending a heartbeat.
[WS => Shard 0] Heartbeat acknowledged, latency of 175ms.

**Comment by FlareEK** [comment]
The bot was coded on an older version of discord.js, so some stuff may have changed :)
